#!/usr/bin/env python3
"""Bake the Inter subset used by GBOT's 240 px usage dashboard.

Requires Pillow 12.3.0 from requirements-dev.txt. Downloads a pinned upstream font into a temporary
directory (or accepts --font), verifies its SHA256, then writes MicroPython
data. No font engine or complete TTF is needed on the board.

Run: python3 scripts/build-limits-font.py --preview artifacts/gbot-fonts.png
"""

from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path
import string
import subprocess
import tempfile
import urllib.request

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
COMMIT = "353b61b9f4430d5f420d56605a6e7993e0941470"
FONT_URL = f"https://raw.githubusercontent.com/rsms/inter/{COMMIT}/docs/font-files/InterVariable.ttf"
FONT_SHA256 = "4989b125924991b90d05b2d16e0e388c48f7d5bb8b30539bbf9c755278d0ccaf"
SCALE = 4
SPECS = (
    ("hero", 72, 500, string.digits + "-"),
    ("unit", 26, 400, "%°C"),
    ("brand", 16, 600, string.ascii_uppercase + string.ascii_lowercase + string.digits + " -_.í"),
    ("small", 12, 500, string.ascii_uppercase + string.ascii_lowercase + string.digits + " .:%-/"),
    ("micro", 9, 500, string.ascii_uppercase + string.digits + " .:%-/"),
)


def encode_runs(image: Image.Image) -> bytes:
    """Nonzero horizontal runs: unsigned bytes (row, x, length, alpha4)."""
    pixels = image.load()
    runs = bytearray()
    for row in range(image.height):
        x = 0
        while x < image.width:
            alpha = pixels[x, row]
            end = x + 1
            while end < image.width and pixels[end, row] == alpha:
                end += 1
            if alpha:
                runs.extend((row, x, end - x, alpha))
            x = end
    return bytes(runs)


def bake_font(path: Path, size: int, weight: int, chars: str):
    font = ImageFont.truetype(str(path), size * SCALE)
    # Inter variable axes: optical size, weight. Keep text's optical size
    # independent of raster supersampling; small type retains wider apertures.
    font.set_variation_by_axes([min(32, max(14, size)), weight])
    boxes = [font.getbbox(char, anchor="ls") for char in chars if char != " "]
    top = math.floor(min(box[1] for box in boxes) / SCALE) - 2
    bottom = math.ceil(max(box[3] for box in boxes) / SCALE) + 2
    left_pad = max(0, -math.floor(min(box[0] for box in boxes) / SCALE))
    glyph_images = {}
    ink_boxes = []
    for char in chars:
        advance = max(1, round(font.getlength(char) / SCALE))
        right = math.ceil(font.getbbox(char, anchor="ls")[2] / SCALE)
        width = max(advance, right) + left_pad + 2
        image = Image.new("L", (width * SCALE, (bottom - top) * SCALE))
        ImageDraw.Draw(image).text(
            (left_pad * SCALE, -top * SCALE), char, font=font,
            fill=255, anchor="ls", stroke_width=0,
        )
        image = image.resize((width, bottom - top), Image.Resampling.LANCZOS)
        image = image.point([min(15, (value * 15 + 127) // 255) for value in range(256)])
        bbox = image.getbbox()
        if bbox:
            ink_boxes.append(bbox)
        glyph_images[char] = (image, advance)

    # A single vertical crop preserves every character's baseline. Side
    # bearings remain in each glyph's x coordinates; spaces carry only advance.
    crop_top = min(box[1] for box in ink_boxes)
    crop_bottom = max(box[3] for box in ink_boxes)
    height = crop_bottom - crop_top
    glyphs = {}
    for char, (image, advance) in glyph_images.items():
        box = image.getbbox()
        if box is None:
            glyphs[char] = (0, advance, b"")
            continue
        width = box[2]
        image = image.crop((0, crop_top, width, crop_bottom))
        glyphs[char] = (width, advance, encode_runs(image))
    return (height, glyphs)


def write_module(fonts, output: Path):
    lines = [
        '"""Inter bitmap subset for GBOT. Generated by scripts/build-limits-font.py.',
        "Copyright (c) 2016 The Inter Project Authors. SIL OFL 1.1:",
        "see fonts/Inter-OFL.txt. Source revision: " + COMMIT + ".",
        "",
        "FONTS[name] = (height, {char: (width, advance, run_bytes)}).",
        "Runs are (row, x, length, alpha4), four unsigned bytes, alpha 1..15.",
        'Glyphs in a font share a baseline. Spaces have no runs."""',
        "",
        "FONTS = {",
    ]
    for name, (height, glyphs) in fonts.items():
        lines.append(f"    {name!r}: ({height}, {{")
        for char, (width, advance, data) in glyphs.items():
            lines.append(f"        {char!r}: ({width}, {advance}, {data!r}),")
        lines.append("    }),")
    lines.append("}\n")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def write_preview(fonts, output: Path):
    image = Image.new("RGB", (560, 245), (7, 11, 16))
    examples = (
        ("brand", "Claude", 22, 16, (215, 145, 113)),
        ("brand", "Codex", 304, 16, (157, 221, 217)),
        ("hero", "84", 19, 49, (244, 240, 234)),
        ("unit", "%", 115, 82, (184, 181, 179)),
        ("hero", "100", 292, 49, (244, 240, 234)),
        ("unit", "%", 420, 82, (184, 181, 179)),
        ("small", "Resets in 2h 34m", 24, 122, (184, 192, 201)),
        ("micro", "SESSION 5H / WEEK 7D", 304, 125, (184, 192, 201)),
        ("small", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", 24, 160, (200, 210, 220)),
        ("small", "abcdefghijklmnopqrstuvwxyz 0123456789 .:%-/", 24, 181, (200, 210, 220)),
        ("micro", "ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789 .:%-/", 24, 210, (200, 210, 220)),
    )
    draw = ImageDraw.Draw(image)
    bg = image.getpixel((0, 0))
    for name, text, x, y, color in examples:
        _, glyphs = fonts[name]
        palette = [tuple(round(a + (b - a) * alpha / 15) for a, b in zip(bg, color)) for alpha in range(16)]
        for char in text:
            _, advance, data = glyphs[char]
            for index in range(0, len(data), 4):
                row, start, length, alpha = data[index:index + 4]
                draw.line((x + start, y + row, x + start + length - 1, y + row), fill=palette[alpha])
            x += advance
    output.parent.mkdir(parents=True, exist_ok=True)
    image.save(output)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, help="Use a previously downloaded pinned InterVariable.ttf")
    parser.add_argument("--output", type=Path, default=ROOT / "firmware/limits_font.py")
    parser.add_argument("--preview", type=Path, help="Optional proof sheet rendered from the baked run data")
    parser.add_argument("--mpy-output", type=Path, help="Also compile the font for MicroPython 1.29")
    parser.add_argument("--mpy-cross", type=Path, default=ROOT / ".venv/bin/mpy-cross", help="Host cross compiler used with --mpy-output")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="gbot-inter-") as temporary:
        path = args.font or Path(temporary) / "InterVariable.ttf"
        if args.font is None:
            urllib.request.urlretrieve(FONT_URL, path)
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual != FONT_SHA256:
            raise SystemExit(f"Unexpected Inter SHA256: {actual}; expected {FONT_SHA256}")
        fonts = {name: bake_font(path, size, weight, chars) for name, size, weight, chars in SPECS}
    write_module(fonts, args.output)
    if args.mpy_output:
        args.mpy_output.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run([
            str(args.mpy_cross), "-msmall-int-bits=31", "-s", "limits_font.py",
            "-o", str(args.mpy_output), str(args.output),
        ], check=True)
    if args.preview:
        write_preview(fonts, args.preview)
    total = 0
    for name, (height, glyphs) in fonts.items():
        payload = sum(len(glyph[2]) for glyph in glyphs.values())
        total += payload
        advances = [glyph[1] for glyph in glyphs.values()]
        print(f"{name}: {len(glyphs)} glyphs, height={height}, advances={min(advances)}..{max(advances)}, runs={payload:,} bytes")
    print(f"Total run data: {total:,} bytes; source: {args.output.stat().st_size:,} bytes -> {args.output}")
    if args.mpy_output:
        print(f"MicroPython bytecode: {args.mpy_output.stat().st_size:,} bytes -> {args.mpy_output}")


if __name__ == "__main__":
    main()
